package dao.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileBaseCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public FileBaseCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_base
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileBaseIdIsNull() {
            addCriterion("file_base_id is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdIsNotNull() {
            addCriterion("file_base_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdEqualTo(String value) {
            addCriterion("file_base_id =", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotEqualTo(String value) {
            addCriterion("file_base_id <>", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdGreaterThan(String value) {
            addCriterion("file_base_id >", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("file_base_id >=", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLessThan(String value) {
            addCriterion("file_base_id <", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLessThanOrEqualTo(String value) {
            addCriterion("file_base_id <=", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLike(String value) {
            addCriterion("file_base_id like", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotLike(String value) {
            addCriterion("file_base_id not like", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdIn(List<String> values) {
            addCriterion("file_base_id in", values, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotIn(List<String> values) {
            addCriterion("file_base_id not in", values, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdBetween(String value1, String value2) {
            addCriterion("file_base_id between", value1, value2, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotBetween(String value1, String value2) {
            addCriterion("file_base_id not between", value1, value2, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathIsNull() {
            addCriterion("file_base_real_path is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathIsNotNull() {
            addCriterion("file_base_real_path is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathEqualTo(String value) {
            addCriterion("file_base_real_path =", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathNotEqualTo(String value) {
            addCriterion("file_base_real_path <>", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathGreaterThan(String value) {
            addCriterion("file_base_real_path >", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("file_base_real_path >=", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathLessThan(String value) {
            addCriterion("file_base_real_path <", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathLessThanOrEqualTo(String value) {
            addCriterion("file_base_real_path <=", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathLike(String value) {
            addCriterion("file_base_real_path like", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathNotLike(String value) {
            addCriterion("file_base_real_path not like", value, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathIn(List<String> values) {
            addCriterion("file_base_real_path in", values, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathNotIn(List<String> values) {
            addCriterion("file_base_real_path not in", values, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathBetween(String value1, String value2) {
            addCriterion("file_base_real_path between", value1, value2, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathNotBetween(String value1, String value2) {
            addCriterion("file_base_real_path not between", value1, value2, "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5IsNull() {
            addCriterion("file_base_md5 is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5IsNotNull() {
            addCriterion("file_base_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5EqualTo(String value) {
            addCriterion("file_base_md5 =", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5NotEqualTo(String value) {
            addCriterion("file_base_md5 <>", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5GreaterThan(String value) {
            addCriterion("file_base_md5 >", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5GreaterThanOrEqualTo(String value) {
            addCriterion("file_base_md5 >=", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5LessThan(String value) {
            addCriterion("file_base_md5 <", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5LessThanOrEqualTo(String value) {
            addCriterion("file_base_md5 <=", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5Like(String value) {
            addCriterion("file_base_md5 like", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5NotLike(String value) {
            addCriterion("file_base_md5 not like", value, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5In(List<String> values) {
            addCriterion("file_base_md5 in", values, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5NotIn(List<String> values) {
            addCriterion("file_base_md5 not in", values, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5Between(String value1, String value2) {
            addCriterion("file_base_md5 between", value1, value2, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5NotBetween(String value1, String value2) {
            addCriterion("file_base_md5 not between", value1, value2, "fileBaseMd5");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateIsNull() {
            addCriterion("file_base_state is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateIsNotNull() {
            addCriterion("file_base_state is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateEqualTo(Byte value) {
            addCriterion("file_base_state =", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateNotEqualTo(Byte value) {
            addCriterion("file_base_state <>", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateGreaterThan(Byte value) {
            addCriterion("file_base_state >", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("file_base_state >=", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateLessThan(Byte value) {
            addCriterion("file_base_state <", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateLessThanOrEqualTo(Byte value) {
            addCriterion("file_base_state <=", value, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateIn(List<Byte> values) {
            addCriterion("file_base_state in", values, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateNotIn(List<Byte> values) {
            addCriterion("file_base_state not in", values, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateBetween(Byte value1, Byte value2) {
            addCriterion("file_base_state between", value1, value2, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseStateNotBetween(Byte value1, Byte value2) {
            addCriterion("file_base_state not between", value1, value2, "fileBaseState");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeIsNull() {
            addCriterion("file_base_total_size is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeIsNotNull() {
            addCriterion("file_base_total_size is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeEqualTo(Long value) {
            addCriterion("file_base_total_size =", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeNotEqualTo(Long value) {
            addCriterion("file_base_total_size <>", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeGreaterThan(Long value) {
            addCriterion("file_base_total_size >", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("file_base_total_size >=", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeLessThan(Long value) {
            addCriterion("file_base_total_size <", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeLessThanOrEqualTo(Long value) {
            addCriterion("file_base_total_size <=", value, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeIn(List<Long> values) {
            addCriterion("file_base_total_size in", values, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeNotIn(List<Long> values) {
            addCriterion("file_base_total_size not in", values, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeBetween(Long value1, Long value2) {
            addCriterion("file_base_total_size between", value1, value2, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBaseTotalSizeNotBetween(Long value1, Long value2) {
            addCriterion("file_base_total_size not between", value1, value2, "fileBaseTotalSize");
            return (Criteria) this;
        }

        public Criteria andFileBasePosIsNull() {
            addCriterion("file_base_pos is null");
            return (Criteria) this;
        }

        public Criteria andFileBasePosIsNotNull() {
            addCriterion("file_base_pos is not null");
            return (Criteria) this;
        }

        public Criteria andFileBasePosEqualTo(Long value) {
            addCriterion("file_base_pos =", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosNotEqualTo(Long value) {
            addCriterion("file_base_pos <>", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosGreaterThan(Long value) {
            addCriterion("file_base_pos >", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosGreaterThanOrEqualTo(Long value) {
            addCriterion("file_base_pos >=", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosLessThan(Long value) {
            addCriterion("file_base_pos <", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosLessThanOrEqualTo(Long value) {
            addCriterion("file_base_pos <=", value, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosIn(List<Long> values) {
            addCriterion("file_base_pos in", values, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosNotIn(List<Long> values) {
            addCriterion("file_base_pos not in", values, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosBetween(Long value1, Long value2) {
            addCriterion("file_base_pos between", value1, value2, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBasePosNotBetween(Long value1, Long value2) {
            addCriterion("file_base_pos not between", value1, value2, "fileBasePos");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeIsNull() {
            addCriterion("file_base_create_time is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeIsNotNull() {
            addCriterion("file_base_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeEqualTo(Date value) {
            addCriterion("file_base_create_time =", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeNotEqualTo(Date value) {
            addCriterion("file_base_create_time <>", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeGreaterThan(Date value) {
            addCriterion("file_base_create_time >", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("file_base_create_time >=", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeLessThan(Date value) {
            addCriterion("file_base_create_time <", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("file_base_create_time <=", value, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeIn(List<Date> values) {
            addCriterion("file_base_create_time in", values, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeNotIn(List<Date> values) {
            addCriterion("file_base_create_time not in", values, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeBetween(Date value1, Date value2) {
            addCriterion("file_base_create_time between", value1, value2, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("file_base_create_time not between", value1, value2, "fileBaseCreateTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeIsNull() {
            addCriterion("file_base_complete_time is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeIsNotNull() {
            addCriterion("file_base_complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeEqualTo(Date value) {
            addCriterion("file_base_complete_time =", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeNotEqualTo(Date value) {
            addCriterion("file_base_complete_time <>", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeGreaterThan(Date value) {
            addCriterion("file_base_complete_time >", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("file_base_complete_time >=", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeLessThan(Date value) {
            addCriterion("file_base_complete_time <", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("file_base_complete_time <=", value, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeIn(List<Date> values) {
            addCriterion("file_base_complete_time in", values, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeNotIn(List<Date> values) {
            addCriterion("file_base_complete_time not in", values, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("file_base_complete_time between", value1, value2, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("file_base_complete_time not between", value1, value2, "fileBaseCompleteTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeIsNull() {
            addCriterion("file_base_next_upload_time is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeIsNotNull() {
            addCriterion("file_base_next_upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeEqualTo(Date value) {
            addCriterion("file_base_next_upload_time =", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeNotEqualTo(Date value) {
            addCriterion("file_base_next_upload_time <>", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeGreaterThan(Date value) {
            addCriterion("file_base_next_upload_time >", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("file_base_next_upload_time >=", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeLessThan(Date value) {
            addCriterion("file_base_next_upload_time <", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("file_base_next_upload_time <=", value, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeIn(List<Date> values) {
            addCriterion("file_base_next_upload_time in", values, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeNotIn(List<Date> values) {
            addCriterion("file_base_next_upload_time not in", values, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeBetween(Date value1, Date value2) {
            addCriterion("file_base_next_upload_time between", value1, value2, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseNextUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("file_base_next_upload_time not between", value1, value2, "fileBaseNextUploadTime");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLikeInsensitive(String value) {
            addCriterion("upper(file_base_id) like", value.toUpperCase(), "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseRealPathLikeInsensitive(String value) {
            addCriterion("upper(file_base_real_path) like", value.toUpperCase(), "fileBaseRealPath");
            return (Criteria) this;
        }

        public Criteria andFileBaseMd5LikeInsensitive(String value) {
            addCriterion("upper(file_base_md5) like", value.toUpperCase(), "fileBaseMd5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_base
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_base
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}