package dao.model.base;

import java.io.Serializable;
import java.util.Date;

public class FileBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_id
     *
     * @mbg.generated
     */
    private String fileBaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_real_path
     *
     * @mbg.generated
     */
    private String fileBaseRealPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_md5
     *
     * @mbg.generated
     */
    private String fileBaseMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_state
     *
     * @mbg.generated
     */
    private Byte fileBaseState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_total_size
     *
     * @mbg.generated
     */
    private Long fileBaseTotalSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_pos
     *
     * @mbg.generated
     */
    private Long fileBasePos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_create_time
     *
     * @mbg.generated
     */
    private Date fileBaseCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_complete_time
     *
     * @mbg.generated
     */
    private Date fileBaseCompleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_base.file_base_next_upload_time
     *
     * @mbg.generated
     */
    private Date fileBaseNextUploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_base
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_id
     *
     * @return the value of file_base.file_base_id
     *
     * @mbg.generated
     */
    public String getFileBaseId() {
        return fileBaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_id
     *
     * @param fileBaseId the value for file_base.file_base_id
     *
     * @mbg.generated
     */
    public void setFileBaseId(String fileBaseId) {
        this.fileBaseId = fileBaseId == null ? null : fileBaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_real_path
     *
     * @return the value of file_base.file_base_real_path
     *
     * @mbg.generated
     */
    public String getFileBaseRealPath() {
        return fileBaseRealPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_real_path
     *
     * @param fileBaseRealPath the value for file_base.file_base_real_path
     *
     * @mbg.generated
     */
    public void setFileBaseRealPath(String fileBaseRealPath) {
        this.fileBaseRealPath = fileBaseRealPath == null ? null : fileBaseRealPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_md5
     *
     * @return the value of file_base.file_base_md5
     *
     * @mbg.generated
     */
    public String getFileBaseMd5() {
        return fileBaseMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_md5
     *
     * @param fileBaseMd5 the value for file_base.file_base_md5
     *
     * @mbg.generated
     */
    public void setFileBaseMd5(String fileBaseMd5) {
        this.fileBaseMd5 = fileBaseMd5 == null ? null : fileBaseMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_state
     *
     * @return the value of file_base.file_base_state
     *
     * @mbg.generated
     */
    public Byte getFileBaseState() {
        return fileBaseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_state
     *
     * @param fileBaseState the value for file_base.file_base_state
     *
     * @mbg.generated
     */
    public void setFileBaseState(Byte fileBaseState) {
        this.fileBaseState = fileBaseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_total_size
     *
     * @return the value of file_base.file_base_total_size
     *
     * @mbg.generated
     */
    public Long getFileBaseTotalSize() {
        return fileBaseTotalSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_total_size
     *
     * @param fileBaseTotalSize the value for file_base.file_base_total_size
     *
     * @mbg.generated
     */
    public void setFileBaseTotalSize(Long fileBaseTotalSize) {
        this.fileBaseTotalSize = fileBaseTotalSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_pos
     *
     * @return the value of file_base.file_base_pos
     *
     * @mbg.generated
     */
    public Long getFileBasePos() {
        return fileBasePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_pos
     *
     * @param fileBasePos the value for file_base.file_base_pos
     *
     * @mbg.generated
     */
    public void setFileBasePos(Long fileBasePos) {
        this.fileBasePos = fileBasePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_create_time
     *
     * @return the value of file_base.file_base_create_time
     *
     * @mbg.generated
     */
    public Date getFileBaseCreateTime() {
        return fileBaseCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_create_time
     *
     * @param fileBaseCreateTime the value for file_base.file_base_create_time
     *
     * @mbg.generated
     */
    public void setFileBaseCreateTime(Date fileBaseCreateTime) {
        this.fileBaseCreateTime = fileBaseCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_complete_time
     *
     * @return the value of file_base.file_base_complete_time
     *
     * @mbg.generated
     */
    public Date getFileBaseCompleteTime() {
        return fileBaseCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_complete_time
     *
     * @param fileBaseCompleteTime the value for file_base.file_base_complete_time
     *
     * @mbg.generated
     */
    public void setFileBaseCompleteTime(Date fileBaseCompleteTime) {
        this.fileBaseCompleteTime = fileBaseCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_base.file_base_next_upload_time
     *
     * @return the value of file_base.file_base_next_upload_time
     *
     * @mbg.generated
     */
    public Date getFileBaseNextUploadTime() {
        return fileBaseNextUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_base.file_base_next_upload_time
     *
     * @param fileBaseNextUploadTime the value for file_base.file_base_next_upload_time
     *
     * @mbg.generated
     */
    public void setFileBaseNextUploadTime(Date fileBaseNextUploadTime) {
        this.fileBaseNextUploadTime = fileBaseNextUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileBase other = (FileBase) that;
        return (this.getFileBaseId() == null ? other.getFileBaseId() == null : this.getFileBaseId().equals(other.getFileBaseId()))
            && (this.getFileBaseRealPath() == null ? other.getFileBaseRealPath() == null : this.getFileBaseRealPath().equals(other.getFileBaseRealPath()))
            && (this.getFileBaseMd5() == null ? other.getFileBaseMd5() == null : this.getFileBaseMd5().equals(other.getFileBaseMd5()))
            && (this.getFileBaseState() == null ? other.getFileBaseState() == null : this.getFileBaseState().equals(other.getFileBaseState()))
            && (this.getFileBaseTotalSize() == null ? other.getFileBaseTotalSize() == null : this.getFileBaseTotalSize().equals(other.getFileBaseTotalSize()))
            && (this.getFileBasePos() == null ? other.getFileBasePos() == null : this.getFileBasePos().equals(other.getFileBasePos()))
            && (this.getFileBaseCreateTime() == null ? other.getFileBaseCreateTime() == null : this.getFileBaseCreateTime().equals(other.getFileBaseCreateTime()))
            && (this.getFileBaseCompleteTime() == null ? other.getFileBaseCompleteTime() == null : this.getFileBaseCompleteTime().equals(other.getFileBaseCompleteTime()))
            && (this.getFileBaseNextUploadTime() == null ? other.getFileBaseNextUploadTime() == null : this.getFileBaseNextUploadTime().equals(other.getFileBaseNextUploadTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_base
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileBaseId() == null) ? 0 : getFileBaseId().hashCode());
        result = prime * result + ((getFileBaseRealPath() == null) ? 0 : getFileBaseRealPath().hashCode());
        result = prime * result + ((getFileBaseMd5() == null) ? 0 : getFileBaseMd5().hashCode());
        result = prime * result + ((getFileBaseState() == null) ? 0 : getFileBaseState().hashCode());
        result = prime * result + ((getFileBaseTotalSize() == null) ? 0 : getFileBaseTotalSize().hashCode());
        result = prime * result + ((getFileBasePos() == null) ? 0 : getFileBasePos().hashCode());
        result = prime * result + ((getFileBaseCreateTime() == null) ? 0 : getFileBaseCreateTime().hashCode());
        result = prime * result + ((getFileBaseCompleteTime() == null) ? 0 : getFileBaseCompleteTime().hashCode());
        result = prime * result + ((getFileBaseNextUploadTime() == null) ? 0 : getFileBaseNextUploadTime().hashCode());
        return result;
    }
}