package dao.model.base;

import java.io.Serializable;

public class UserBoxinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_boxinfo.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_boxinfo.box_size_offset
     *
     * @mbg.generated
     */
    private Integer boxSizeOffset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_boxinfo.user_id
     *
     * @return the value of user_boxinfo.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_boxinfo.user_id
     *
     * @param userId the value for user_boxinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_boxinfo.box_size_offset
     *
     * @return the value of user_boxinfo.box_size_offset
     *
     * @mbg.generated
     */
    public Integer getBoxSizeOffset() {
        return boxSizeOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_boxinfo.box_size_offset
     *
     * @param boxSizeOffset the value for user_boxinfo.box_size_offset
     *
     * @mbg.generated
     */
    public void setBoxSizeOffset(Integer boxSizeOffset) {
        this.boxSizeOffset = boxSizeOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBoxinfo other = (UserBoxinfo) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBoxSizeOffset() == null ? other.getBoxSizeOffset() == null : this.getBoxSizeOffset().equals(other.getBoxSizeOffset()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBoxSizeOffset() == null) ? 0 : getBoxSizeOffset().hashCode());
        return result;
    }
}