package dao.model.base;

import java.io.Serializable;
import java.util.Date;

public class UserFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_file_id
     *
     * @mbg.generated
     */
    private String userFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_file_name
     *
     * @mbg.generated
     */
    private String userFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_fold_parent_id
     *
     * @mbg.generated
     */
    private String userFoldParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_file_create_time
     *
     * @mbg.generated
     */
    private Date userFileCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_file_update_time
     *
     * @mbg.generated
     */
    private Date userFileUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_file_state
     *
     * @mbg.generated
     */
    private Byte userFileState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_fold_top_id
     *
     * @mbg.generated
     */
    private String userFoldTopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_base_id
     *
     * @mbg.generated
     */
    private String fileBaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_file_id
     *
     * @return the value of user_file.user_file_id
     *
     * @mbg.generated
     */
    public String getUserFileId() {
        return userFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_file_id
     *
     * @param userFileId the value for user_file.user_file_id
     *
     * @mbg.generated
     */
    public void setUserFileId(String userFileId) {
        this.userFileId = userFileId == null ? null : userFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_file_name
     *
     * @return the value of user_file.user_file_name
     *
     * @mbg.generated
     */
    public String getUserFileName() {
        return userFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_file_name
     *
     * @param userFileName the value for user_file.user_file_name
     *
     * @mbg.generated
     */
    public void setUserFileName(String userFileName) {
        this.userFileName = userFileName == null ? null : userFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_fold_parent_id
     *
     * @return the value of user_file.user_fold_parent_id
     *
     * @mbg.generated
     */
    public String getUserFoldParentId() {
        return userFoldParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_fold_parent_id
     *
     * @param userFoldParentId the value for user_file.user_fold_parent_id
     *
     * @mbg.generated
     */
    public void setUserFoldParentId(String userFoldParentId) {
        this.userFoldParentId = userFoldParentId == null ? null : userFoldParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_file_create_time
     *
     * @return the value of user_file.user_file_create_time
     *
     * @mbg.generated
     */
    public Date getUserFileCreateTime() {
        return userFileCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_file_create_time
     *
     * @param userFileCreateTime the value for user_file.user_file_create_time
     *
     * @mbg.generated
     */
    public void setUserFileCreateTime(Date userFileCreateTime) {
        this.userFileCreateTime = userFileCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_file_update_time
     *
     * @return the value of user_file.user_file_update_time
     *
     * @mbg.generated
     */
    public Date getUserFileUpdateTime() {
        return userFileUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_file_update_time
     *
     * @param userFileUpdateTime the value for user_file.user_file_update_time
     *
     * @mbg.generated
     */
    public void setUserFileUpdateTime(Date userFileUpdateTime) {
        this.userFileUpdateTime = userFileUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_file_state
     *
     * @return the value of user_file.user_file_state
     *
     * @mbg.generated
     */
    public Byte getUserFileState() {
        return userFileState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_file_state
     *
     * @param userFileState the value for user_file.user_file_state
     *
     * @mbg.generated
     */
    public void setUserFileState(Byte userFileState) {
        this.userFileState = userFileState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_fold_top_id
     *
     * @return the value of user_file.user_fold_top_id
     *
     * @mbg.generated
     */
    public String getUserFoldTopId() {
        return userFoldTopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_fold_top_id
     *
     * @param userFoldTopId the value for user_file.user_fold_top_id
     *
     * @mbg.generated
     */
    public void setUserFoldTopId(String userFoldTopId) {
        this.userFoldTopId = userFoldTopId == null ? null : userFoldTopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.create_user_id
     *
     * @return the value of user_file.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.create_user_id
     *
     * @param createUserId the value for user_file.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_base_id
     *
     * @return the value of user_file.file_base_id
     *
     * @mbg.generated
     */
    public String getFileBaseId() {
        return fileBaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_base_id
     *
     * @param fileBaseId the value for user_file.file_base_id
     *
     * @mbg.generated
     */
    public void setFileBaseId(String fileBaseId) {
        this.fileBaseId = fileBaseId == null ? null : fileBaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserFile other = (UserFile) that;
        return (this.getUserFileId() == null ? other.getUserFileId() == null : this.getUserFileId().equals(other.getUserFileId()))
            && (this.getUserFileName() == null ? other.getUserFileName() == null : this.getUserFileName().equals(other.getUserFileName()))
            && (this.getUserFoldParentId() == null ? other.getUserFoldParentId() == null : this.getUserFoldParentId().equals(other.getUserFoldParentId()))
            && (this.getUserFileCreateTime() == null ? other.getUserFileCreateTime() == null : this.getUserFileCreateTime().equals(other.getUserFileCreateTime()))
            && (this.getUserFileUpdateTime() == null ? other.getUserFileUpdateTime() == null : this.getUserFileUpdateTime().equals(other.getUserFileUpdateTime()))
            && (this.getUserFileState() == null ? other.getUserFileState() == null : this.getUserFileState().equals(other.getUserFileState()))
            && (this.getUserFoldTopId() == null ? other.getUserFoldTopId() == null : this.getUserFoldTopId().equals(other.getUserFoldTopId()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getFileBaseId() == null ? other.getFileBaseId() == null : this.getFileBaseId().equals(other.getFileBaseId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserFileId() == null) ? 0 : getUserFileId().hashCode());
        result = prime * result + ((getUserFileName() == null) ? 0 : getUserFileName().hashCode());
        result = prime * result + ((getUserFoldParentId() == null) ? 0 : getUserFoldParentId().hashCode());
        result = prime * result + ((getUserFileCreateTime() == null) ? 0 : getUserFileCreateTime().hashCode());
        result = prime * result + ((getUserFileUpdateTime() == null) ? 0 : getUserFileUpdateTime().hashCode());
        result = prime * result + ((getUserFileState() == null) ? 0 : getUserFileState().hashCode());
        result = prime * result + ((getUserFoldTopId() == null) ? 0 : getUserFoldTopId().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getFileBaseId() == null) ? 0 : getFileBaseId().hashCode());
        return result;
    }
}