package dao.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserFileCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public UserFileCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_file
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserFileIdIsNull() {
            addCriterion("user_file_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFileIdIsNotNull() {
            addCriterion("user_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFileIdEqualTo(String value) {
            addCriterion("user_file_id =", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdNotEqualTo(String value) {
            addCriterion("user_file_id <>", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdGreaterThan(String value) {
            addCriterion("user_file_id >", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_file_id >=", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdLessThan(String value) {
            addCriterion("user_file_id <", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdLessThanOrEqualTo(String value) {
            addCriterion("user_file_id <=", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdLike(String value) {
            addCriterion("user_file_id like", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdNotLike(String value) {
            addCriterion("user_file_id not like", value, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdIn(List<String> values) {
            addCriterion("user_file_id in", values, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdNotIn(List<String> values) {
            addCriterion("user_file_id not in", values, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdBetween(String value1, String value2) {
            addCriterion("user_file_id between", value1, value2, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdNotBetween(String value1, String value2) {
            addCriterion("user_file_id not between", value1, value2, "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileNameIsNull() {
            addCriterion("user_file_name is null");
            return (Criteria) this;
        }

        public Criteria andUserFileNameIsNotNull() {
            addCriterion("user_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserFileNameEqualTo(String value) {
            addCriterion("user_file_name =", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameNotEqualTo(String value) {
            addCriterion("user_file_name <>", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameGreaterThan(String value) {
            addCriterion("user_file_name >", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_file_name >=", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameLessThan(String value) {
            addCriterion("user_file_name <", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameLessThanOrEqualTo(String value) {
            addCriterion("user_file_name <=", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameLike(String value) {
            addCriterion("user_file_name like", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameNotLike(String value) {
            addCriterion("user_file_name not like", value, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameIn(List<String> values) {
            addCriterion("user_file_name in", values, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameNotIn(List<String> values) {
            addCriterion("user_file_name not in", values, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameBetween(String value1, String value2) {
            addCriterion("user_file_name between", value1, value2, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFileNameNotBetween(String value1, String value2) {
            addCriterion("user_file_name not between", value1, value2, "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIsNull() {
            addCriterion("user_fold_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIsNotNull() {
            addCriterion("user_fold_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdEqualTo(String value) {
            addCriterion("user_fold_parent_id =", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotEqualTo(String value) {
            addCriterion("user_fold_parent_id <>", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdGreaterThan(String value) {
            addCriterion("user_fold_parent_id >", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_parent_id >=", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLessThan(String value) {
            addCriterion("user_fold_parent_id <", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_parent_id <=", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLike(String value) {
            addCriterion("user_fold_parent_id like", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotLike(String value) {
            addCriterion("user_fold_parent_id not like", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIn(List<String> values) {
            addCriterion("user_fold_parent_id in", values, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotIn(List<String> values) {
            addCriterion("user_fold_parent_id not in", values, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdBetween(String value1, String value2) {
            addCriterion("user_fold_parent_id between", value1, value2, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_parent_id not between", value1, value2, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeIsNull() {
            addCriterion("user_file_create_time is null");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeIsNotNull() {
            addCriterion("user_file_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeEqualTo(Date value) {
            addCriterion("user_file_create_time =", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeNotEqualTo(Date value) {
            addCriterion("user_file_create_time <>", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeGreaterThan(Date value) {
            addCriterion("user_file_create_time >", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_file_create_time >=", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeLessThan(Date value) {
            addCriterion("user_file_create_time <", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_file_create_time <=", value, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeIn(List<Date> values) {
            addCriterion("user_file_create_time in", values, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeNotIn(List<Date> values) {
            addCriterion("user_file_create_time not in", values, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeBetween(Date value1, Date value2) {
            addCriterion("user_file_create_time between", value1, value2, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_file_create_time not between", value1, value2, "userFileCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeIsNull() {
            addCriterion("user_file_update_time is null");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeIsNotNull() {
            addCriterion("user_file_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeEqualTo(Date value) {
            addCriterion("user_file_update_time =", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeNotEqualTo(Date value) {
            addCriterion("user_file_update_time <>", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeGreaterThan(Date value) {
            addCriterion("user_file_update_time >", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_file_update_time >=", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeLessThan(Date value) {
            addCriterion("user_file_update_time <", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_file_update_time <=", value, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeIn(List<Date> values) {
            addCriterion("user_file_update_time in", values, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeNotIn(List<Date> values) {
            addCriterion("user_file_update_time not in", values, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("user_file_update_time between", value1, value2, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_file_update_time not between", value1, value2, "userFileUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFileStateIsNull() {
            addCriterion("user_file_state is null");
            return (Criteria) this;
        }

        public Criteria andUserFileStateIsNotNull() {
            addCriterion("user_file_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserFileStateEqualTo(Byte value) {
            addCriterion("user_file_state =", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateNotEqualTo(Byte value) {
            addCriterion("user_file_state <>", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateGreaterThan(Byte value) {
            addCriterion("user_file_state >", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_file_state >=", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateLessThan(Byte value) {
            addCriterion("user_file_state <", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateLessThanOrEqualTo(Byte value) {
            addCriterion("user_file_state <=", value, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateIn(List<Byte> values) {
            addCriterion("user_file_state in", values, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateNotIn(List<Byte> values) {
            addCriterion("user_file_state not in", values, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateBetween(Byte value1, Byte value2) {
            addCriterion("user_file_state between", value1, value2, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFileStateNotBetween(Byte value1, Byte value2) {
            addCriterion("user_file_state not between", value1, value2, "userFileState");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIsNull() {
            addCriterion("user_fold_top_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIsNotNull() {
            addCriterion("user_fold_top_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdEqualTo(String value) {
            addCriterion("user_fold_top_id =", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotEqualTo(String value) {
            addCriterion("user_fold_top_id <>", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdGreaterThan(String value) {
            addCriterion("user_fold_top_id >", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_top_id >=", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLessThan(String value) {
            addCriterion("user_fold_top_id <", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_top_id <=", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLike(String value) {
            addCriterion("user_fold_top_id like", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotLike(String value) {
            addCriterion("user_fold_top_id not like", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIn(List<String> values) {
            addCriterion("user_fold_top_id in", values, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotIn(List<String> values) {
            addCriterion("user_fold_top_id not in", values, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdBetween(String value1, String value2) {
            addCriterion("user_fold_top_id between", value1, value2, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_top_id not between", value1, value2, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdIsNull() {
            addCriterion("file_base_id is null");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdIsNotNull() {
            addCriterion("file_base_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdEqualTo(String value) {
            addCriterion("file_base_id =", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotEqualTo(String value) {
            addCriterion("file_base_id <>", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdGreaterThan(String value) {
            addCriterion("file_base_id >", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("file_base_id >=", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLessThan(String value) {
            addCriterion("file_base_id <", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLessThanOrEqualTo(String value) {
            addCriterion("file_base_id <=", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLike(String value) {
            addCriterion("file_base_id like", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotLike(String value) {
            addCriterion("file_base_id not like", value, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdIn(List<String> values) {
            addCriterion("file_base_id in", values, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotIn(List<String> values) {
            addCriterion("file_base_id not in", values, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdBetween(String value1, String value2) {
            addCriterion("file_base_id between", value1, value2, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdNotBetween(String value1, String value2) {
            addCriterion("file_base_id not between", value1, value2, "fileBaseId");
            return (Criteria) this;
        }

        public Criteria andUserFileIdLikeInsensitive(String value) {
            addCriterion("upper(user_file_id) like", value.toUpperCase(), "userFileId");
            return (Criteria) this;
        }

        public Criteria andUserFileNameLikeInsensitive(String value) {
            addCriterion("upper(user_file_name) like", value.toUpperCase(), "userFileName");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_parent_id) like", value.toUpperCase(), "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_top_id) like", value.toUpperCase(), "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLikeInsensitive(String value) {
            addCriterion("upper(create_user_id) like", value.toUpperCase(), "createUserId");
            return (Criteria) this;
        }

        public Criteria andFileBaseIdLikeInsensitive(String value) {
            addCriterion("upper(file_base_id) like", value.toUpperCase(), "fileBaseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_file
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_file
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}