package dao.model.base;

import java.io.Serializable;
import java.util.Date;

public class UserFold implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_id
     *
     * @mbg.generated
     */
    private String userFoldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_name
     *
     * @mbg.generated
     */
    private String userFoldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_parent_id
     *
     * @mbg.generated
     */
    private String userFoldParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_create_time
     *
     * @mbg.generated
     */
    private Date userFoldCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_update_time
     *
     * @mbg.generated
     */
    private Date userFoldUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_state
     *
     * @mbg.generated
     */
    private Byte userFoldState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_top_id
     *
     * @mbg.generated
     */
    private String userFoldTopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_owner_type
     *
     * @mbg.generated
     */
    private Byte userFoldOwnerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_owner_id
     *
     * @mbg.generated
     */
    private String userFoldOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_channel_type
     *
     * @mbg.generated
     */
    private Byte userFoldChannelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fold.user_fold_channel_user_id
     *
     * @mbg.generated
     */
    private String userFoldChannelUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_id
     *
     * @return the value of user_fold.user_fold_id
     *
     * @mbg.generated
     */
    public String getUserFoldId() {
        return userFoldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_id
     *
     * @param userFoldId the value for user_fold.user_fold_id
     *
     * @mbg.generated
     */
    public void setUserFoldId(String userFoldId) {
        this.userFoldId = userFoldId == null ? null : userFoldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_name
     *
     * @return the value of user_fold.user_fold_name
     *
     * @mbg.generated
     */
    public String getUserFoldName() {
        return userFoldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_name
     *
     * @param userFoldName the value for user_fold.user_fold_name
     *
     * @mbg.generated
     */
    public void setUserFoldName(String userFoldName) {
        this.userFoldName = userFoldName == null ? null : userFoldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_parent_id
     *
     * @return the value of user_fold.user_fold_parent_id
     *
     * @mbg.generated
     */
    public String getUserFoldParentId() {
        return userFoldParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_parent_id
     *
     * @param userFoldParentId the value for user_fold.user_fold_parent_id
     *
     * @mbg.generated
     */
    public void setUserFoldParentId(String userFoldParentId) {
        this.userFoldParentId = userFoldParentId == null ? null : userFoldParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_create_time
     *
     * @return the value of user_fold.user_fold_create_time
     *
     * @mbg.generated
     */
    public Date getUserFoldCreateTime() {
        return userFoldCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_create_time
     *
     * @param userFoldCreateTime the value for user_fold.user_fold_create_time
     *
     * @mbg.generated
     */
    public void setUserFoldCreateTime(Date userFoldCreateTime) {
        this.userFoldCreateTime = userFoldCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_update_time
     *
     * @return the value of user_fold.user_fold_update_time
     *
     * @mbg.generated
     */
    public Date getUserFoldUpdateTime() {
        return userFoldUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_update_time
     *
     * @param userFoldUpdateTime the value for user_fold.user_fold_update_time
     *
     * @mbg.generated
     */
    public void setUserFoldUpdateTime(Date userFoldUpdateTime) {
        this.userFoldUpdateTime = userFoldUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_state
     *
     * @return the value of user_fold.user_fold_state
     *
     * @mbg.generated
     */
    public Byte getUserFoldState() {
        return userFoldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_state
     *
     * @param userFoldState the value for user_fold.user_fold_state
     *
     * @mbg.generated
     */
    public void setUserFoldState(Byte userFoldState) {
        this.userFoldState = userFoldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_top_id
     *
     * @return the value of user_fold.user_fold_top_id
     *
     * @mbg.generated
     */
    public String getUserFoldTopId() {
        return userFoldTopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_top_id
     *
     * @param userFoldTopId the value for user_fold.user_fold_top_id
     *
     * @mbg.generated
     */
    public void setUserFoldTopId(String userFoldTopId) {
        this.userFoldTopId = userFoldTopId == null ? null : userFoldTopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.create_user_id
     *
     * @return the value of user_fold.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.create_user_id
     *
     * @param createUserId the value for user_fold.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_owner_type
     *
     * @return the value of user_fold.user_fold_owner_type
     *
     * @mbg.generated
     */
    public Byte getUserFoldOwnerType() {
        return userFoldOwnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_owner_type
     *
     * @param userFoldOwnerType the value for user_fold.user_fold_owner_type
     *
     * @mbg.generated
     */
    public void setUserFoldOwnerType(Byte userFoldOwnerType) {
        this.userFoldOwnerType = userFoldOwnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_owner_id
     *
     * @return the value of user_fold.user_fold_owner_id
     *
     * @mbg.generated
     */
    public String getUserFoldOwnerId() {
        return userFoldOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_owner_id
     *
     * @param userFoldOwnerId the value for user_fold.user_fold_owner_id
     *
     * @mbg.generated
     */
    public void setUserFoldOwnerId(String userFoldOwnerId) {
        this.userFoldOwnerId = userFoldOwnerId == null ? null : userFoldOwnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_channel_type
     *
     * @return the value of user_fold.user_fold_channel_type
     *
     * @mbg.generated
     */
    public Byte getUserFoldChannelType() {
        return userFoldChannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_channel_type
     *
     * @param userFoldChannelType the value for user_fold.user_fold_channel_type
     *
     * @mbg.generated
     */
    public void setUserFoldChannelType(Byte userFoldChannelType) {
        this.userFoldChannelType = userFoldChannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fold.user_fold_channel_user_id
     *
     * @return the value of user_fold.user_fold_channel_user_id
     *
     * @mbg.generated
     */
    public String getUserFoldChannelUserId() {
        return userFoldChannelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fold.user_fold_channel_user_id
     *
     * @param userFoldChannelUserId the value for user_fold.user_fold_channel_user_id
     *
     * @mbg.generated
     */
    public void setUserFoldChannelUserId(String userFoldChannelUserId) {
        this.userFoldChannelUserId = userFoldChannelUserId == null ? null : userFoldChannelUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserFold other = (UserFold) that;
        return (this.getUserFoldId() == null ? other.getUserFoldId() == null : this.getUserFoldId().equals(other.getUserFoldId()))
            && (this.getUserFoldName() == null ? other.getUserFoldName() == null : this.getUserFoldName().equals(other.getUserFoldName()))
            && (this.getUserFoldParentId() == null ? other.getUserFoldParentId() == null : this.getUserFoldParentId().equals(other.getUserFoldParentId()))
            && (this.getUserFoldCreateTime() == null ? other.getUserFoldCreateTime() == null : this.getUserFoldCreateTime().equals(other.getUserFoldCreateTime()))
            && (this.getUserFoldUpdateTime() == null ? other.getUserFoldUpdateTime() == null : this.getUserFoldUpdateTime().equals(other.getUserFoldUpdateTime()))
            && (this.getUserFoldState() == null ? other.getUserFoldState() == null : this.getUserFoldState().equals(other.getUserFoldState()))
            && (this.getUserFoldTopId() == null ? other.getUserFoldTopId() == null : this.getUserFoldTopId().equals(other.getUserFoldTopId()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getUserFoldOwnerType() == null ? other.getUserFoldOwnerType() == null : this.getUserFoldOwnerType().equals(other.getUserFoldOwnerType()))
            && (this.getUserFoldOwnerId() == null ? other.getUserFoldOwnerId() == null : this.getUserFoldOwnerId().equals(other.getUserFoldOwnerId()))
            && (this.getUserFoldChannelType() == null ? other.getUserFoldChannelType() == null : this.getUserFoldChannelType().equals(other.getUserFoldChannelType()))
            && (this.getUserFoldChannelUserId() == null ? other.getUserFoldChannelUserId() == null : this.getUserFoldChannelUserId().equals(other.getUserFoldChannelUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserFoldId() == null) ? 0 : getUserFoldId().hashCode());
        result = prime * result + ((getUserFoldName() == null) ? 0 : getUserFoldName().hashCode());
        result = prime * result + ((getUserFoldParentId() == null) ? 0 : getUserFoldParentId().hashCode());
        result = prime * result + ((getUserFoldCreateTime() == null) ? 0 : getUserFoldCreateTime().hashCode());
        result = prime * result + ((getUserFoldUpdateTime() == null) ? 0 : getUserFoldUpdateTime().hashCode());
        result = prime * result + ((getUserFoldState() == null) ? 0 : getUserFoldState().hashCode());
        result = prime * result + ((getUserFoldTopId() == null) ? 0 : getUserFoldTopId().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getUserFoldOwnerType() == null) ? 0 : getUserFoldOwnerType().hashCode());
        result = prime * result + ((getUserFoldOwnerId() == null) ? 0 : getUserFoldOwnerId().hashCode());
        result = prime * result + ((getUserFoldChannelType() == null) ? 0 : getUserFoldChannelType().hashCode());
        result = prime * result + ((getUserFoldChannelUserId() == null) ? 0 : getUserFoldChannelUserId().hashCode());
        return result;
    }
}