package dao.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserFoldCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public UserFoldCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserFoldIdIsNull() {
            addCriterion("user_fold_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdIsNotNull() {
            addCriterion("user_fold_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdEqualTo(String value) {
            addCriterion("user_fold_id =", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdNotEqualTo(String value) {
            addCriterion("user_fold_id <>", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdGreaterThan(String value) {
            addCriterion("user_fold_id >", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_id >=", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdLessThan(String value) {
            addCriterion("user_fold_id <", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_id <=", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdLike(String value) {
            addCriterion("user_fold_id like", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdNotLike(String value) {
            addCriterion("user_fold_id not like", value, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdIn(List<String> values) {
            addCriterion("user_fold_id in", values, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdNotIn(List<String> values) {
            addCriterion("user_fold_id not in", values, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdBetween(String value1, String value2) {
            addCriterion("user_fold_id between", value1, value2, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_id not between", value1, value2, "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameIsNull() {
            addCriterion("user_fold_name is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameIsNotNull() {
            addCriterion("user_fold_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameEqualTo(String value) {
            addCriterion("user_fold_name =", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameNotEqualTo(String value) {
            addCriterion("user_fold_name <>", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameGreaterThan(String value) {
            addCriterion("user_fold_name >", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_name >=", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameLessThan(String value) {
            addCriterion("user_fold_name <", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameLessThanOrEqualTo(String value) {
            addCriterion("user_fold_name <=", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameLike(String value) {
            addCriterion("user_fold_name like", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameNotLike(String value) {
            addCriterion("user_fold_name not like", value, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameIn(List<String> values) {
            addCriterion("user_fold_name in", values, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameNotIn(List<String> values) {
            addCriterion("user_fold_name not in", values, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameBetween(String value1, String value2) {
            addCriterion("user_fold_name between", value1, value2, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameNotBetween(String value1, String value2) {
            addCriterion("user_fold_name not between", value1, value2, "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIsNull() {
            addCriterion("user_fold_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIsNotNull() {
            addCriterion("user_fold_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdEqualTo(String value) {
            addCriterion("user_fold_parent_id =", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotEqualTo(String value) {
            addCriterion("user_fold_parent_id <>", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdGreaterThan(String value) {
            addCriterion("user_fold_parent_id >", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_parent_id >=", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLessThan(String value) {
            addCriterion("user_fold_parent_id <", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_parent_id <=", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLike(String value) {
            addCriterion("user_fold_parent_id like", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotLike(String value) {
            addCriterion("user_fold_parent_id not like", value, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdIn(List<String> values) {
            addCriterion("user_fold_parent_id in", values, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotIn(List<String> values) {
            addCriterion("user_fold_parent_id not in", values, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdBetween(String value1, String value2) {
            addCriterion("user_fold_parent_id between", value1, value2, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_parent_id not between", value1, value2, "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeIsNull() {
            addCriterion("user_fold_create_time is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeIsNotNull() {
            addCriterion("user_fold_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeEqualTo(Date value) {
            addCriterion("user_fold_create_time =", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeNotEqualTo(Date value) {
            addCriterion("user_fold_create_time <>", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeGreaterThan(Date value) {
            addCriterion("user_fold_create_time >", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_fold_create_time >=", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeLessThan(Date value) {
            addCriterion("user_fold_create_time <", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_fold_create_time <=", value, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeIn(List<Date> values) {
            addCriterion("user_fold_create_time in", values, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeNotIn(List<Date> values) {
            addCriterion("user_fold_create_time not in", values, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeBetween(Date value1, Date value2) {
            addCriterion("user_fold_create_time between", value1, value2, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_fold_create_time not between", value1, value2, "userFoldCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeIsNull() {
            addCriterion("user_fold_update_time is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeIsNotNull() {
            addCriterion("user_fold_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeEqualTo(Date value) {
            addCriterion("user_fold_update_time =", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeNotEqualTo(Date value) {
            addCriterion("user_fold_update_time <>", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeGreaterThan(Date value) {
            addCriterion("user_fold_update_time >", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_fold_update_time >=", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeLessThan(Date value) {
            addCriterion("user_fold_update_time <", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_fold_update_time <=", value, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeIn(List<Date> values) {
            addCriterion("user_fold_update_time in", values, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeNotIn(List<Date> values) {
            addCriterion("user_fold_update_time not in", values, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("user_fold_update_time between", value1, value2, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_fold_update_time not between", value1, value2, "userFoldUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateIsNull() {
            addCriterion("user_fold_state is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateIsNotNull() {
            addCriterion("user_fold_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateEqualTo(Byte value) {
            addCriterion("user_fold_state =", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateNotEqualTo(Byte value) {
            addCriterion("user_fold_state <>", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateGreaterThan(Byte value) {
            addCriterion("user_fold_state >", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_fold_state >=", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateLessThan(Byte value) {
            addCriterion("user_fold_state <", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateLessThanOrEqualTo(Byte value) {
            addCriterion("user_fold_state <=", value, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateIn(List<Byte> values) {
            addCriterion("user_fold_state in", values, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateNotIn(List<Byte> values) {
            addCriterion("user_fold_state not in", values, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_state between", value1, value2, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldStateNotBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_state not between", value1, value2, "userFoldState");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIsNull() {
            addCriterion("user_fold_top_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIsNotNull() {
            addCriterion("user_fold_top_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdEqualTo(String value) {
            addCriterion("user_fold_top_id =", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotEqualTo(String value) {
            addCriterion("user_fold_top_id <>", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdGreaterThan(String value) {
            addCriterion("user_fold_top_id >", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_top_id >=", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLessThan(String value) {
            addCriterion("user_fold_top_id <", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_top_id <=", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLike(String value) {
            addCriterion("user_fold_top_id like", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotLike(String value) {
            addCriterion("user_fold_top_id not like", value, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdIn(List<String> values) {
            addCriterion("user_fold_top_id in", values, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotIn(List<String> values) {
            addCriterion("user_fold_top_id not in", values, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdBetween(String value1, String value2) {
            addCriterion("user_fold_top_id between", value1, value2, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_top_id not between", value1, value2, "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeIsNull() {
            addCriterion("user_fold_owner_type is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeIsNotNull() {
            addCriterion("user_fold_owner_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeEqualTo(Byte value) {
            addCriterion("user_fold_owner_type =", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeNotEqualTo(Byte value) {
            addCriterion("user_fold_owner_type <>", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeGreaterThan(Byte value) {
            addCriterion("user_fold_owner_type >", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_fold_owner_type >=", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeLessThan(Byte value) {
            addCriterion("user_fold_owner_type <", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeLessThanOrEqualTo(Byte value) {
            addCriterion("user_fold_owner_type <=", value, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeIn(List<Byte> values) {
            addCriterion("user_fold_owner_type in", values, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeNotIn(List<Byte> values) {
            addCriterion("user_fold_owner_type not in", values, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_owner_type between", value1, value2, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_owner_type not between", value1, value2, "userFoldOwnerType");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdIsNull() {
            addCriterion("user_fold_owner_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdIsNotNull() {
            addCriterion("user_fold_owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdEqualTo(String value) {
            addCriterion("user_fold_owner_id =", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdNotEqualTo(String value) {
            addCriterion("user_fold_owner_id <>", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdGreaterThan(String value) {
            addCriterion("user_fold_owner_id >", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_owner_id >=", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdLessThan(String value) {
            addCriterion("user_fold_owner_id <", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_owner_id <=", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdLike(String value) {
            addCriterion("user_fold_owner_id like", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdNotLike(String value) {
            addCriterion("user_fold_owner_id not like", value, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdIn(List<String> values) {
            addCriterion("user_fold_owner_id in", values, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdNotIn(List<String> values) {
            addCriterion("user_fold_owner_id not in", values, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdBetween(String value1, String value2) {
            addCriterion("user_fold_owner_id between", value1, value2, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_owner_id not between", value1, value2, "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeIsNull() {
            addCriterion("user_fold_channel_type is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeIsNotNull() {
            addCriterion("user_fold_channel_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeEqualTo(Byte value) {
            addCriterion("user_fold_channel_type =", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeNotEqualTo(Byte value) {
            addCriterion("user_fold_channel_type <>", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeGreaterThan(Byte value) {
            addCriterion("user_fold_channel_type >", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_fold_channel_type >=", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeLessThan(Byte value) {
            addCriterion("user_fold_channel_type <", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeLessThanOrEqualTo(Byte value) {
            addCriterion("user_fold_channel_type <=", value, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeIn(List<Byte> values) {
            addCriterion("user_fold_channel_type in", values, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeNotIn(List<Byte> values) {
            addCriterion("user_fold_channel_type not in", values, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_channel_type between", value1, value2, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_fold_channel_type not between", value1, value2, "userFoldChannelType");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdIsNull() {
            addCriterion("user_fold_channel_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdIsNotNull() {
            addCriterion("user_fold_channel_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdEqualTo(String value) {
            addCriterion("user_fold_channel_user_id =", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdNotEqualTo(String value) {
            addCriterion("user_fold_channel_user_id <>", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdGreaterThan(String value) {
            addCriterion("user_fold_channel_user_id >", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_fold_channel_user_id >=", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdLessThan(String value) {
            addCriterion("user_fold_channel_user_id <", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_fold_channel_user_id <=", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdLike(String value) {
            addCriterion("user_fold_channel_user_id like", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdNotLike(String value) {
            addCriterion("user_fold_channel_user_id not like", value, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdIn(List<String> values) {
            addCriterion("user_fold_channel_user_id in", values, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdNotIn(List<String> values) {
            addCriterion("user_fold_channel_user_id not in", values, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdBetween(String value1, String value2) {
            addCriterion("user_fold_channel_user_id between", value1, value2, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdNotBetween(String value1, String value2) {
            addCriterion("user_fold_channel_user_id not between", value1, value2, "userFoldChannelUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_id) like", value.toUpperCase(), "userFoldId");
            return (Criteria) this;
        }

        public Criteria andUserFoldNameLikeInsensitive(String value) {
            addCriterion("upper(user_fold_name) like", value.toUpperCase(), "userFoldName");
            return (Criteria) this;
        }

        public Criteria andUserFoldParentIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_parent_id) like", value.toUpperCase(), "userFoldParentId");
            return (Criteria) this;
        }

        public Criteria andUserFoldTopIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_top_id) like", value.toUpperCase(), "userFoldTopId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLikeInsensitive(String value) {
            addCriterion("upper(create_user_id) like", value.toUpperCase(), "createUserId");
            return (Criteria) this;
        }

        public Criteria andUserFoldOwnerIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_owner_id) like", value.toUpperCase(), "userFoldOwnerId");
            return (Criteria) this;
        }

        public Criteria andUserFoldChannelUserIdLikeInsensitive(String value) {
            addCriterion("upper(user_fold_channel_user_id) like", value.toUpperCase(), "userFoldChannelUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_fold
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}