package dao.dao.base;

import dao.model.base.UserFile;
import dao.model.base.UserFileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    long countByExample(UserFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int deleteByExample(UserFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int insert(UserFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int insertSelective(UserFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    List<UserFile> selectByExample(UserFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    UserFile selectByPrimaryKey(String userFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserFile record, @Param("example") UserFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserFile record, @Param("example") UserFileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFile record);
}