package dao.dao.base;

import dao.model.base.UserBoxinfo;
import dao.model.base.UserBoxinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBoxinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    long countByExample(UserBoxinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int deleteByExample(UserBoxinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int insert(UserBoxinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int insertSelective(UserBoxinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    List<UserBoxinfo> selectByExample(UserBoxinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    UserBoxinfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBoxinfo record, @Param("example") UserBoxinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBoxinfo record, @Param("example") UserBoxinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBoxinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_boxinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBoxinfo record);
}