package dao.dao.base;

import dao.model.base.UserFold;
import dao.model.base.UserFoldCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFoldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    long countByExample(UserFoldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int deleteByExample(UserFoldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userFoldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int insert(UserFold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int insertSelective(UserFold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    List<UserFold> selectByExample(UserFoldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    UserFold selectByPrimaryKey(String userFoldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserFold record, @Param("example") UserFoldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserFold record, @Param("example") UserFoldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fold
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFold record);
}