// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoxInfoProto.proto

package protobuf.http;

public final class BoxInfoProto {
  private BoxInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoxInfoCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.BoxInfoC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    java.lang.String getUserFoldTopId();
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserFoldTopIdBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.BoxInfoC}
   */
  public  static final class BoxInfoC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.BoxInfoC)
      BoxInfoCOrBuilder {
    // Use BoxInfoC.newBuilder() to construct.
    private BoxInfoC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoxInfoC() {
      hOpCode_ = "";
      userFoldTopId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BoxInfoC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userFoldTopId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.BoxInfoProto.BoxInfoC.class, protobuf.http.BoxInfoProto.BoxInfoC.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERFOLDTOPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userFoldTopId_;
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public java.lang.String getUserFoldTopId() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userFoldTopId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserFoldTopIdBytes() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userFoldTopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userFoldTopId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userFoldTopId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.BoxInfoProto.BoxInfoC)) {
        return super.equals(obj);
      }
      protobuf.http.BoxInfoProto.BoxInfoC other = (protobuf.http.BoxInfoProto.BoxInfoC) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getUserFoldTopId()
          .equals(other.getUserFoldTopId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + USERFOLDTOPID_FIELD_NUMBER;
      hash = (53 * hash) + getUserFoldTopId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.BoxInfoProto.BoxInfoC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.BoxInfoC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.BoxInfoC)
        protobuf.http.BoxInfoProto.BoxInfoCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.BoxInfoProto.BoxInfoC.class, protobuf.http.BoxInfoProto.BoxInfoC.Builder.class);
      }

      // Construct using protobuf.http.BoxInfoProto.BoxInfoC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        userFoldTopId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoC_descriptor;
      }

      public protobuf.http.BoxInfoProto.BoxInfoC getDefaultInstanceForType() {
        return protobuf.http.BoxInfoProto.BoxInfoC.getDefaultInstance();
      }

      public protobuf.http.BoxInfoProto.BoxInfoC build() {
        protobuf.http.BoxInfoProto.BoxInfoC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.BoxInfoProto.BoxInfoC buildPartial() {
        protobuf.http.BoxInfoProto.BoxInfoC result = new protobuf.http.BoxInfoProto.BoxInfoC(this);
        result.hOpCode_ = hOpCode_;
        result.userFoldTopId_ = userFoldTopId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.BoxInfoProto.BoxInfoC) {
          return mergeFrom((protobuf.http.BoxInfoProto.BoxInfoC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.BoxInfoProto.BoxInfoC other) {
        if (other == protobuf.http.BoxInfoProto.BoxInfoC.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getUserFoldTopId().isEmpty()) {
          userFoldTopId_ = other.userFoldTopId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.BoxInfoProto.BoxInfoC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.BoxInfoProto.BoxInfoC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userFoldTopId_ = "";
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public java.lang.String getUserFoldTopId() {
        java.lang.Object ref = userFoldTopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userFoldTopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserFoldTopIdBytes() {
        java.lang.Object ref = userFoldTopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userFoldTopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userFoldTopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder clearUserFoldTopId() {
        
        userFoldTopId_ = getDefaultInstance().getUserFoldTopId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userFoldTopId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.BoxInfoC)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.BoxInfoC)
    private static final protobuf.http.BoxInfoProto.BoxInfoC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.BoxInfoProto.BoxInfoC();
    }

    public static protobuf.http.BoxInfoProto.BoxInfoC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoxInfoC>
        PARSER = new com.google.protobuf.AbstractParser<BoxInfoC>() {
      public BoxInfoC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BoxInfoC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoxInfoC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoxInfoC> getParserForType() {
      return PARSER;
    }

    public protobuf.http.BoxInfoProto.BoxInfoC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoxInfoSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.BoxInfoS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    java.lang.String getUserFoldTopId();
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserFoldTopIdBytes();

    /**
     * <pre>
     *已使用大小
     * </pre>
     *
     * <code>optional int32 useSize = 3;</code>
     */
    int getUseSize();

    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional int32 totalSize = 4;</code>
     */
    int getTotalSize();
  }
  /**
   * Protobuf type {@code protobuf.http.BoxInfoS}
   */
  public  static final class BoxInfoS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.BoxInfoS)
      BoxInfoSOrBuilder {
    // Use BoxInfoS.newBuilder() to construct.
    private BoxInfoS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoxInfoS() {
      hOpCode_ = "";
      userFoldTopId_ = "";
      useSize_ = 0;
      totalSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BoxInfoS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userFoldTopId_ = s;
              break;
            }
            case 24: {

              useSize_ = input.readInt32();
              break;
            }
            case 32: {

              totalSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.BoxInfoProto.BoxInfoS.class, protobuf.http.BoxInfoProto.BoxInfoS.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERFOLDTOPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userFoldTopId_;
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public java.lang.String getUserFoldTopId() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userFoldTopId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserFoldTopIdBytes() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userFoldTopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USESIZE_FIELD_NUMBER = 3;
    private int useSize_;
    /**
     * <pre>
     *已使用大小
     * </pre>
     *
     * <code>optional int32 useSize = 3;</code>
     */
    public int getUseSize() {
      return useSize_;
    }

    public static final int TOTALSIZE_FIELD_NUMBER = 4;
    private int totalSize_;
    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional int32 totalSize = 4;</code>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userFoldTopId_);
      }
      if (useSize_ != 0) {
        output.writeInt32(3, useSize_);
      }
      if (totalSize_ != 0) {
        output.writeInt32(4, totalSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userFoldTopId_);
      }
      if (useSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, useSize_);
      }
      if (totalSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.BoxInfoProto.BoxInfoS)) {
        return super.equals(obj);
      }
      protobuf.http.BoxInfoProto.BoxInfoS other = (protobuf.http.BoxInfoProto.BoxInfoS) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getUserFoldTopId()
          .equals(other.getUserFoldTopId());
      result = result && (getUseSize()
          == other.getUseSize());
      result = result && (getTotalSize()
          == other.getTotalSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + USERFOLDTOPID_FIELD_NUMBER;
      hash = (53 * hash) + getUserFoldTopId().hashCode();
      hash = (37 * hash) + USESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getUseSize();
      hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.BoxInfoProto.BoxInfoS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.BoxInfoProto.BoxInfoS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.BoxInfoS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.BoxInfoS)
        protobuf.http.BoxInfoProto.BoxInfoSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.BoxInfoProto.BoxInfoS.class, protobuf.http.BoxInfoProto.BoxInfoS.Builder.class);
      }

      // Construct using protobuf.http.BoxInfoProto.BoxInfoS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        userFoldTopId_ = "";

        useSize_ = 0;

        totalSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.BoxInfoProto.internal_static_protobuf_http_BoxInfoS_descriptor;
      }

      public protobuf.http.BoxInfoProto.BoxInfoS getDefaultInstanceForType() {
        return protobuf.http.BoxInfoProto.BoxInfoS.getDefaultInstance();
      }

      public protobuf.http.BoxInfoProto.BoxInfoS build() {
        protobuf.http.BoxInfoProto.BoxInfoS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.BoxInfoProto.BoxInfoS buildPartial() {
        protobuf.http.BoxInfoProto.BoxInfoS result = new protobuf.http.BoxInfoProto.BoxInfoS(this);
        result.hOpCode_ = hOpCode_;
        result.userFoldTopId_ = userFoldTopId_;
        result.useSize_ = useSize_;
        result.totalSize_ = totalSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.BoxInfoProto.BoxInfoS) {
          return mergeFrom((protobuf.http.BoxInfoProto.BoxInfoS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.BoxInfoProto.BoxInfoS other) {
        if (other == protobuf.http.BoxInfoProto.BoxInfoS.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getUserFoldTopId().isEmpty()) {
          userFoldTopId_ = other.userFoldTopId_;
          onChanged();
        }
        if (other.getUseSize() != 0) {
          setUseSize(other.getUseSize());
        }
        if (other.getTotalSize() != 0) {
          setTotalSize(other.getTotalSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.BoxInfoProto.BoxInfoS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.BoxInfoProto.BoxInfoS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userFoldTopId_ = "";
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public java.lang.String getUserFoldTopId() {
        java.lang.Object ref = userFoldTopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userFoldTopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserFoldTopIdBytes() {
        java.lang.Object ref = userFoldTopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userFoldTopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userFoldTopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder clearUserFoldTopId() {
        
        userFoldTopId_ = getDefaultInstance().getUserFoldTopId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userFoldTopId_ = value;
        onChanged();
        return this;
      }

      private int useSize_ ;
      /**
       * <pre>
       *已使用大小
       * </pre>
       *
       * <code>optional int32 useSize = 3;</code>
       */
      public int getUseSize() {
        return useSize_;
      }
      /**
       * <pre>
       *已使用大小
       * </pre>
       *
       * <code>optional int32 useSize = 3;</code>
       */
      public Builder setUseSize(int value) {
        
        useSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已使用大小
       * </pre>
       *
       * <code>optional int32 useSize = 3;</code>
       */
      public Builder clearUseSize() {
        
        useSize_ = 0;
        onChanged();
        return this;
      }

      private int totalSize_ ;
      /**
       * <pre>
       *总大小
       * </pre>
       *
       * <code>optional int32 totalSize = 4;</code>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <pre>
       *总大小
       * </pre>
       *
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder setTotalSize(int value) {
        
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总大小
       * </pre>
       *
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder clearTotalSize() {
        
        totalSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.BoxInfoS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.BoxInfoS)
    private static final protobuf.http.BoxInfoProto.BoxInfoS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.BoxInfoProto.BoxInfoS();
    }

    public static protobuf.http.BoxInfoProto.BoxInfoS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoxInfoS>
        PARSER = new com.google.protobuf.AbstractParser<BoxInfoS>() {
      public BoxInfoS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BoxInfoS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoxInfoS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoxInfoS> getParserForType() {
      return PARSER;
    }

    public protobuf.http.BoxInfoProto.BoxInfoS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_BoxInfoC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_BoxInfoC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_BoxInfoS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_BoxInfoS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BoxInfoProto.proto\022\rprotobuf.http\"2\n\010B" +
      "oxInfoC\022\017\n\007hOpCode\030\001 \001(\t\022\025\n\ruserFoldTopI" +
      "d\030\002 \001(\t\"V\n\010BoxInfoS\022\017\n\007hOpCode\030\001 \001(\t\022\025\n\r" +
      "userFoldTopId\030\002 \001(\t\022\017\n\007useSize\030\003 \001(\005\022\021\n\t" +
      "totalSize\030\004 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_http_BoxInfoC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_http_BoxInfoC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_BoxInfoC_descriptor,
        new java.lang.String[] { "HOpCode", "UserFoldTopId", });
    internal_static_protobuf_http_BoxInfoS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_http_BoxInfoS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_BoxInfoS_descriptor,
        new java.lang.String[] { "HOpCode", "UserFoldTopId", "UseSize", "TotalSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
