// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginProto.proto

package protobuf.http;

public final class LoginProto {
  private LoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.LoginC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional int32 type = 3;</code>
     */
    int getType();

    /**
     * <code>optional int32 boxsize = 4;</code>
     */
    int getBoxsize();
  }
  /**
   * Protobuf type {@code protobuf.http.LoginC}
   */
  public  static final class LoginC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.LoginC)
      LoginCOrBuilder {
    // Use LoginC.newBuilder() to construct.
    private LoginC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginC() {
      hOpCode_ = "";
      token_ = "";
      type_ = 0;
      boxsize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 32: {

              boxsize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.LoginProto.internal_static_protobuf_http_LoginC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.LoginProto.internal_static_protobuf_http_LoginC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.LoginProto.LoginC.class, protobuf.http.LoginProto.LoginC.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int BOXSIZE_FIELD_NUMBER = 4;
    private int boxsize_;
    /**
     * <code>optional int32 boxsize = 4;</code>
     */
    public int getBoxsize() {
      return boxsize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (boxsize_ != 0) {
        output.writeInt32(4, boxsize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (boxsize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, boxsize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.LoginProto.LoginC)) {
        return super.equals(obj);
      }
      protobuf.http.LoginProto.LoginC other = (protobuf.http.LoginProto.LoginC) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getType()
          == other.getType());
      result = result && (getBoxsize()
          == other.getBoxsize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + BOXSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBoxsize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.LoginProto.LoginC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.LoginProto.LoginC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.LoginC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.LoginC)
        protobuf.http.LoginProto.LoginCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.LoginProto.LoginC.class, protobuf.http.LoginProto.LoginC.Builder.class);
      }

      // Construct using protobuf.http.LoginProto.LoginC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        token_ = "";

        type_ = 0;

        boxsize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginC_descriptor;
      }

      public protobuf.http.LoginProto.LoginC getDefaultInstanceForType() {
        return protobuf.http.LoginProto.LoginC.getDefaultInstance();
      }

      public protobuf.http.LoginProto.LoginC build() {
        protobuf.http.LoginProto.LoginC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.LoginProto.LoginC buildPartial() {
        protobuf.http.LoginProto.LoginC result = new protobuf.http.LoginProto.LoginC(this);
        result.hOpCode_ = hOpCode_;
        result.token_ = token_;
        result.type_ = type_;
        result.boxsize_ = boxsize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.LoginProto.LoginC) {
          return mergeFrom((protobuf.http.LoginProto.LoginC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.LoginProto.LoginC other) {
        if (other == protobuf.http.LoginProto.LoginC.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getBoxsize() != 0) {
          setBoxsize(other.getBoxsize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.LoginProto.LoginC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.LoginProto.LoginC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int boxsize_ ;
      /**
       * <code>optional int32 boxsize = 4;</code>
       */
      public int getBoxsize() {
        return boxsize_;
      }
      /**
       * <code>optional int32 boxsize = 4;</code>
       */
      public Builder setBoxsize(int value) {
        
        boxsize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 boxsize = 4;</code>
       */
      public Builder clearBoxsize() {
        
        boxsize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.LoginC)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.LoginC)
    private static final protobuf.http.LoginProto.LoginC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.LoginProto.LoginC();
    }

    public static protobuf.http.LoginProto.LoginC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginC>
        PARSER = new com.google.protobuf.AbstractParser<LoginC>() {
      public LoginC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginC> getParserForType() {
      return PARSER;
    }

    public protobuf.http.LoginProto.LoginC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.LoginS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hOpCode = 1;</code>
     */
    java.lang.String getHOpCode();
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getHOpCodeBytes();

    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    java.lang.String getUserFoldTopId();
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserFoldTopIdBytes();

    /**
     * <code>optional string userId = 3;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string userRealName = 4;</code>
     */
    java.lang.String getUserRealName();
    /**
     * <code>optional string userRealName = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserRealNameBytes();

    /**
     * <code>optional string userImgUrl = 5;</code>
     */
    java.lang.String getUserImgUrl();
    /**
     * <code>optional string userImgUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserImgUrlBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.LoginS}
   */
  public  static final class LoginS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.LoginS)
      LoginSOrBuilder {
    // Use LoginS.newBuilder() to construct.
    private LoginS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginS() {
      hOpCode_ = "";
      userFoldTopId_ = "";
      userId_ = "";
      userRealName_ = "";
      userImgUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hOpCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userFoldTopId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userRealName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userImgUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.LoginProto.internal_static_protobuf_http_LoginS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.LoginProto.internal_static_protobuf_http_LoginS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.LoginProto.LoginS.class, protobuf.http.LoginProto.LoginS.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hOpCode_;
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public java.lang.String getHOpCode() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hOpCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hOpCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHOpCodeBytes() {
      java.lang.Object ref = hOpCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hOpCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERFOLDTOPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userFoldTopId_;
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public java.lang.String getUserFoldTopId() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userFoldTopId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userFoldTopId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserFoldTopIdBytes() {
      java.lang.Object ref = userFoldTopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userFoldTopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 3;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERREALNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userRealName_;
    /**
     * <code>optional string userRealName = 4;</code>
     */
    public java.lang.String getUserRealName() {
      java.lang.Object ref = userRealName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userRealName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userRealName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserRealNameBytes() {
      java.lang.Object ref = userRealName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userRealName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERIMGURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object userImgUrl_;
    /**
     * <code>optional string userImgUrl = 5;</code>
     */
    public java.lang.String getUserImgUrl() {
      java.lang.Object ref = userImgUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userImgUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userImgUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserImgUrlBytes() {
      java.lang.Object ref = userImgUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userImgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHOpCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userFoldTopId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
      }
      if (!getUserRealNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userRealName_);
      }
      if (!getUserImgUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userImgUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHOpCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hOpCode_);
      }
      if (!getUserFoldTopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userFoldTopId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
      }
      if (!getUserRealNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userRealName_);
      }
      if (!getUserImgUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userImgUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.LoginProto.LoginS)) {
        return super.equals(obj);
      }
      protobuf.http.LoginProto.LoginS other = (protobuf.http.LoginProto.LoginS) obj;

      boolean result = true;
      result = result && getHOpCode()
          .equals(other.getHOpCode());
      result = result && getUserFoldTopId()
          .equals(other.getUserFoldTopId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getUserRealName()
          .equals(other.getUserRealName());
      result = result && getUserImgUrl()
          .equals(other.getUserImgUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode().hashCode();
      hash = (37 * hash) + USERFOLDTOPID_FIELD_NUMBER;
      hash = (53 * hash) + getUserFoldTopId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + USERREALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserRealName().hashCode();
      hash = (37 * hash) + USERIMGURL_FIELD_NUMBER;
      hash = (53 * hash) + getUserImgUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.LoginProto.LoginS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.LoginProto.LoginS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.LoginProto.LoginS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.LoginS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.LoginS)
        protobuf.http.LoginProto.LoginSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.LoginProto.LoginS.class, protobuf.http.LoginProto.LoginS.Builder.class);
      }

      // Construct using protobuf.http.LoginProto.LoginS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = "";

        userFoldTopId_ = "";

        userId_ = "";

        userRealName_ = "";

        userImgUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.LoginProto.internal_static_protobuf_http_LoginS_descriptor;
      }

      public protobuf.http.LoginProto.LoginS getDefaultInstanceForType() {
        return protobuf.http.LoginProto.LoginS.getDefaultInstance();
      }

      public protobuf.http.LoginProto.LoginS build() {
        protobuf.http.LoginProto.LoginS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.LoginProto.LoginS buildPartial() {
        protobuf.http.LoginProto.LoginS result = new protobuf.http.LoginProto.LoginS(this);
        result.hOpCode_ = hOpCode_;
        result.userFoldTopId_ = userFoldTopId_;
        result.userId_ = userId_;
        result.userRealName_ = userRealName_;
        result.userImgUrl_ = userImgUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.LoginProto.LoginS) {
          return mergeFrom((protobuf.http.LoginProto.LoginS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.LoginProto.LoginS other) {
        if (other == protobuf.http.LoginProto.LoginS.getDefaultInstance()) return this;
        if (!other.getHOpCode().isEmpty()) {
          hOpCode_ = other.hOpCode_;
          onChanged();
        }
        if (!other.getUserFoldTopId().isEmpty()) {
          userFoldTopId_ = other.userFoldTopId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getUserRealName().isEmpty()) {
          userRealName_ = other.userRealName_;
          onChanged();
        }
        if (!other.getUserImgUrl().isEmpty()) {
          userImgUrl_ = other.userImgUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.LoginProto.LoginS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.LoginProto.LoginS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hOpCode_ = "";
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public java.lang.String getHOpCode() {
        java.lang.Object ref = hOpCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hOpCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHOpCodeBytes() {
        java.lang.Object ref = hOpCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hOpCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = getDefaultInstance().getHOpCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hOpCode = 1;</code>
       */
      public Builder setHOpCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hOpCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userFoldTopId_ = "";
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public java.lang.String getUserFoldTopId() {
        java.lang.Object ref = userFoldTopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userFoldTopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserFoldTopIdBytes() {
        java.lang.Object ref = userFoldTopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userFoldTopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userFoldTopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder clearUserFoldTopId() {
        
        userFoldTopId_ = getDefaultInstance().getUserFoldTopId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userFoldTopId = 2;</code>
       */
      public Builder setUserFoldTopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userFoldTopId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 3;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userRealName_ = "";
      /**
       * <code>optional string userRealName = 4;</code>
       */
      public java.lang.String getUserRealName() {
        java.lang.Object ref = userRealName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userRealName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userRealName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserRealNameBytes() {
        java.lang.Object ref = userRealName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userRealName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userRealName = 4;</code>
       */
      public Builder setUserRealName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userRealName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userRealName = 4;</code>
       */
      public Builder clearUserRealName() {
        
        userRealName_ = getDefaultInstance().getUserRealName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userRealName = 4;</code>
       */
      public Builder setUserRealNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userRealName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userImgUrl_ = "";
      /**
       * <code>optional string userImgUrl = 5;</code>
       */
      public java.lang.String getUserImgUrl() {
        java.lang.Object ref = userImgUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userImgUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userImgUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserImgUrlBytes() {
        java.lang.Object ref = userImgUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userImgUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userImgUrl = 5;</code>
       */
      public Builder setUserImgUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userImgUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userImgUrl = 5;</code>
       */
      public Builder clearUserImgUrl() {
        
        userImgUrl_ = getDefaultInstance().getUserImgUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userImgUrl = 5;</code>
       */
      public Builder setUserImgUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userImgUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.LoginS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.LoginS)
    private static final protobuf.http.LoginProto.LoginS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.LoginProto.LoginS();
    }

    public static protobuf.http.LoginProto.LoginS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginS>
        PARSER = new com.google.protobuf.AbstractParser<LoginS>() {
      public LoginS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginS> getParserForType() {
      return PARSER;
    }

    public protobuf.http.LoginProto.LoginS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_LoginC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_LoginC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_LoginS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_LoginS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020LoginProto.proto\022\rprotobuf.http\"G\n\006Log" +
      "inC\022\017\n\007hOpCode\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\014\n\004t" +
      "ype\030\003 \001(\005\022\017\n\007boxsize\030\004 \001(\005\"j\n\006LoginS\022\017\n\007" +
      "hOpCode\030\001 \001(\t\022\025\n\ruserFoldTopId\030\002 \001(\t\022\016\n\006" +
      "userId\030\003 \001(\t\022\024\n\014userRealName\030\004 \001(\t\022\022\n\nus" +
      "erImgUrl\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_http_LoginC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_http_LoginC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_LoginC_descriptor,
        new java.lang.String[] { "HOpCode", "Token", "Type", "Boxsize", });
    internal_static_protobuf_http_LoginS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_http_LoginS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_LoginS_descriptor,
        new java.lang.String[] { "HOpCode", "UserFoldTopId", "UserId", "UserRealName", "UserImgUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
